### ISSUE TITLE
ICE 问题

### ISSUE THREAD

**Issue by linKnowEasy** [notedit/janus-gateway-ios#1]
你好. 我下载使用了这个demo, 在实际使用中碰到了一些问题, 能回答一下么。

在 WebRTCPeer.m 中
didChangeIceGatheringState 和 didGenerateIceCandidate 回调没有触发。 是什么原因呢？

 [_peerconnection addIceCandidate:candidate] 这个方法没有被调用。。那这个方法的作用是什么呢？

**Comment by notedit** [comment]
这个是要跟我自己写的后端 配合  我封装了一下janus的api.

didGenerateIceCandidate 会触发的  我已经能跑起来.

addIceCandidate 为什么没调用?   janus 的实现不需要这个    candidate 已经在offer 或者 answer里了

**Comment by notedit** [comment]
这个只是一个demo   离一个非常完备的实现 还差很多

**Comment by linKnowEasy** [comment]
哦哦, 好的. 谢谢

**Comment by linKnowEasy** [comment]
你好，能再请教一个问题么？
我现在是和服务端信令交互成功了。 但是卡在多媒体数据发送和接收。
按照网上其他人的流程, 只要 local 和 remote sdp 设置成功之后, 多媒体流就会自动发送。
```
 - (void)peerConnection:(RTCPeerConnection *)peerConnection
          didAddStream:(RTCMediaStream *)stream 
```
这个回调已经触发了。 但是  stream.videoTracks[0]  的 source 却为 nil ,  就是 [track addRenderer:peer.view]; 之后没有图像和声音

**Comment by notedit** [comment]
这个我不太清楚了   我这个例子可以跑通

**Comment by linKnowEasy** [comment]
嗯, 多谢回复。

**Comment by notedit** [comment]
你们的sdk做到什么程度了

**Comment by linKnowEasy** [comment]
在跑通接口。在做 demo

**Comment by fukemy** [comment]
Hi. Can you help me how to open video from ios, with room from Janus : https://janus.conf.meetecho.com/videoroomtest.html
